spring:
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.0:8848
        namespace: ab3ce511-965b-4423-98b7-782925ac83ed
        group: SUPPORT
      discovery:
        server-addr: 127.0.0.0:8848
        namespace: ab3ce511-965b-4423-98b7-782925ac83ed
        group: SUPPORT
  config:
    import:
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yml?refreshEnabled=true