spring:
  cloud:
    nacos:
      config:
        server-addr: 116.62.50.80:8848
        namespace: ab3ce511-965b-4423-98b7-782925ac83ed
        group: BUSINESS
      #注册中心地址
      discovery:
        server-addr: 116.62.50.80:8848
        namespace: ab3ce511-965b-4423-98b7-782925ac83ed
        group: BUSINESS
  config:
    import:
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yml?refreshEnabled=true
logging:
  level:
    org.zh.business.admin: debug

